var dependencies = {
          links:
            [
{ "source" : "Fiori Mobile Experience Service", "dest" : "Fiori Mobile Experience Service" },
{ "source" : "Fiori Mobile Experience Service", "dest" : "Cloud Packager" },
{ "source" : "Fiori Mobile Experience Service", "dest" : "Cloud Build Service" },
{ "source" : "Fiori Mobile Experience Service", "dest" : "Analytics Service" },
{ "source" : "Fiori Mobile Experience Service", "dest" : "Monitoring Service" },
{ "source" : "Fiori Mobile Experience Service", "dest" : "Mobile Secure DB Service" },
{ "source" : "Fiori Mobile Experience Service", "dest" : "Admin UI Component (MAM)" },
{ "source" : "Fiori Mobile Experience Service", "dest" : "Sensu Client" },
{ "source" : "Fiori Mobile Experience Service", "dest" : "Unified Shell Runtime Container" },
{ "source" : "Fiori Mobile Experience Service", "dest" : "Apache" },
{ "source" : "Fiori Mobile Experience Service", "dest" : "Redhat VM" },
{ "source" : "MDM Service", "dest" : "Monitoring Service" },
{ "source" : "MDM Service", "dest" : "Mobile Secure DB Service" },
{ "source" : "MDM Service", "dest" : "MDM Service" },
{ "source" : "MDM Service", "dest" : "APNS" },
{ "source" : "MDM Service", "dest" : "GCM" },
{ "source" : "MDM Service", "dest" : "WNS" },
{ "source" : "MDM Service", "dest" : "Apple App Store" },
{ "source" : "MDM Service", "dest" : "Google Play" },
{ "source" : "MDM Service", "dest" : "Windows App Store" },
{ "source" : "MDM Service", "dest" : "Enterprise Connectivity Service" },
{ "source" : "MDM Service", "dest" : "Sensu Client" },
{ "source" : "MDM Service", "dest" : "Afaria iOS Client" },
{ "source" : "MDM Service", "dest" : "Afaria Android Client" },
{ "source" : "MDM Service", "dest" : "Afaria Win32 Client" },
{ "source" : "MDM Service", "dest" : "SAML SSO" },
{ "source" : "MDM Service", "dest" : "Windows VM" },
{ "source" : "MDM Service", "dest" : "Certificate Authority?" },
{ "source" : "MDM Service", "dest" : "Open SSH / Cygwin" },
{ "source" : "MDM Service", "dest" : "MobiLink Client" },
{ "source" : "Cloud Build Service", "dest" : "Fiori Mobile Experience Service" },
{ "source" : "Cloud Build Service", "dest" : "Cloud Build Service" },
{ "source" : "Cloud Build Service", "dest" : "Analytics Service" },
{ "source" : "Cloud Build Service", "dest" : "Monitoring Service" },
{ "source" : "Cloud Build Service", "dest" : "Mobile Secure DB Service" },
{ "source" : "Cloud Build Service", "dest" : "Certificate Repository Service" },
{ "source" : "Cloud Build Service", "dest" : "Logging Service" },
{ "source" : "Cloud Build Service", "dest" : "GlusterFS" },
{ "source" : "Cloud Build Service", "dest" : "Public Plugin Service (NPM)" },
{ "source" : "Cloud Build Service", "dest" : "Sensu Client" },
{ "source" : "Cloud Build Service", "dest" : "Apache" },
{ "source" : "Cloud Build Service", "dest" : "Plugins UI" },
{ "source" : "Cloud Build Service", "dest" : "Cloud Build Service Console" },
{ "source" : "Cloud Build Service", "dest" : "SAP Kapsel SDK" },
{ "source" : "Cloud Build Service", "dest" : "Cordova" },
{ "source" : "Cloud Build Service", "dest" : "MacOS" },
{ "source" : "Cloud Build Service", "dest" : "Docker" },
{ "source" : "Cloud Build Service", "dest" : "Android SDK" },
{ "source" : "Cloud Build Service", "dest" : "Xcode" },
{ "source" : "Mobile Place Service", "dest" : "Monitoring Service" },
{ "source" : "Mobile Place Service", "dest" : "Mobile Secure DB Service" },
{ "source" : "Mobile Place Service", "dest" : "MDM Service" },
{ "source" : "Mobile Place Service", "dest" : "Apple App Store" },
{ "source" : "Mobile Place Service", "dest" : "Google Play" },
{ "source" : "Mobile Place Service", "dest" : "Windows App Store" },
{ "source" : "Mobile Place Service", "dest" : "App Protection Service" },
{ "source" : "Mobile Place Service", "dest" : "MCI" },
{ "source" : "Mobile Place Service", "dest" : "Mobile Place Service" },
{ "source" : "Mobile Place Service", "dest" : "Sensu Client" },
{ "source" : "Mobile Place Service", "dest" : "Apache" },
{ "source" : "Mobile Place Service", "dest" : "Redhat VM" },
{ "source" : "Mobile Place Service", "dest" : "Mobile Place Application" },
{ "source" : "Analytics Service", "dest" : "Analytics Service" },
{ "source" : "Analytics Service", "dest" : "Mobile Secure DB Service" },
{ "source" : "Analytics Service", "dest" : "Event Service" },
{ "source" : "Analytics Service", "dest" : "HANA DB Service" },
{ "source" : "Analytics Service", "dest" : "Sensu Client" },
{ "source" : "Analytics Service", "dest" : "MobiLink Client" },
{ "source" : "Analytics Service", "dest" : "ElasticSearch" },
{ "source" : "Analytics Service", "dest" : "Logstash" },
{ "source" : "Analytics Service", "dest" : "RabbitMQ" },
{ "source" : "Analytics Service", "dest" : "Kibana" },
{ "source" : "Analytics Service", "dest" : "Lumira Server" },
{ "source" : "Analytics Service", "dest" : "MobiLink Server" },
{ "source" : "Cloud Persistence Service", "dest" : "Analytics Service" },
{ "source" : "Cloud Persistence Service", "dest" : "Monitoring Service" },
{ "source" : "Cloud Persistence Service", "dest" : "Logging Service" },
{ "source" : "Cloud Persistence Service", "dest" : "Cloud Persistence Service" },
{ "source" : "Cloud Persistence Service", "dest" : "Sensu Client" },
{ "source" : "Cloud Persistence Service", "dest" : "Apache" },
{ "source" : "Cloud Persistence Service", "dest" : "Redhat VM" },
{ "source" : "Cloud Persistence Service", "dest" : "Docker" },
{ "source" : "Cloud Persistence Service", "dest" : "ElasticSearch" },
{ "source" : "Cloud Persistence Service", "dest" : "Persistence API" },
{ "source" : "Cloud Persistence Service", "dest" : "Persistence Sample App" },
{ "source" : "Cloud Persistence Service", "dest" : "Cassandra" },
{ "source" : "Cloud Persistence Service", "dest" : "UserGrid" },
{ "source" : "Cloud Persistence Service", "dest" : "Tomcat" },
{ "source" : "MAMKIT", "dest" : "Analytics Service" },
{ "source" : "MAMKIT", "dest" : "Discovery Service" },
{ "source" : "MAMKIT", "dest" : "Config Provider API" },
{ "source" : "MAMKIT", "dest" : "MAMKit Sample App" },
{ "source" : "Discovery Service", "dest" : "Analytics Service" },
{ "source" : "Discovery Service", "dest" : "Monitoring Service" },
{ "source" : "Discovery Service", "dest" : "Sensu Client" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Cloud Packager" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Cloud Build Service" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Analytics Service" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Cloud Persistence Service" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Discovery Service" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Web IDE Plugin Service" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "API Management Service" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Offline Service" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Push Notification Service" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Login Service" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "SAP Kapsel SDK" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Cordova" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Web IDE External Plugin" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Web IDE UI Components" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Web IDE Companion App" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Web IDE Sample App" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "Fiori Launchpad" },
{ "source" : "Fiori Mobile DevX / WebIDE", "dest" : "UI5 Library" },
{ "source" : "Event App", "dest" : "Fiori Mobile Experience Service" },
{ "source" : "Event App", "dest" : "Analytics Service" },
{ "source" : "Event App", "dest" : "Monitoring Service" },
{ "source" : "Event App", "dest" : "Logging Service" },
{ "source" : "Event App", "dest" : "Event Management Service" },
{ "source" : "Event App", "dest" : "HCPms for Dev & Ops" },
{ "source" : "Event App", "dest" : "Mobile Place Service" },
{ "source" : "Event App", "dest" : "Document Service" },
{ "source" : "Event App", "dest" : "Event App" },
{ "source" : "Cloud Logic Service", "dest" : "Analytics Service" },
{ "source" : "Cloud Logic Service", "dest" : "Monitoring Service" },
{ "source" : "Cloud Logic Service", "dest" : "Logging Service" },
{ "source" : "Cloud Logic Service", "dest" : "API Management Service" },
{ "source" : "Cloud Logic Service", "dest" : "Cloud Logic Service" },
{ "source" : "Cloud Logic Service", "dest" : "Sensu Client" },
]
      }
      ;
